apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalelite-deployment
  labels:
    app: sclte-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sclte
  template:
    metadata:
      labels:
        app: sclte
    spec:
      containers:
      - name: sclte
        image: blindsidenetwks/scalelite:master-nginx
        ports:
        - containerPort: 80 #Port?